# Generated by Django 5.0.6 on 2024-06-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('N_trail_dashboard', '0011_alter_experiment_dsm_sat_alter_experiment_dsm_uav_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='View_Type',
            field=models.CharField(choices=[('', 'select'), ('private', 'Private'), ('protected', 'Protected')], default='private', max_length=10),
        ),
    ]
