# Generated by Django 5.0.6 on 2024-06-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('N_trail_dashboard', '0014_plot_units_plot_yield'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='csv_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='csv_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
