# Generated by Django 5.0.6 on 2024-06-28 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('N_trail_dashboard', '0015_treatment_csv_file_name_treatment_csv_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='csv_file_name',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='csv_file_path',
        ),
    ]
