# Generated by Django 5.0.6 on 2024-05-30 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('Location_ID', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='Location_ID')),
                ('State', models.CharField(max_length=120, verbose_name='State')),
                ('County', models.CharField(max_length=120, verbose_name='County')),
                ('Owner', models.CharField(max_length=120, verbose_name='Owner')),
                ('Latitude', models.CharField(max_length=120, verbose_name='Latitude')),
                ('Longitude', models.CharField(max_length=120, verbose_name='Longitude')),
                ('Contact', models.CharField(max_length=120, verbose_name='Contact')),
                ('MetaData', models.TextField(max_length=120, verbose_name='MetaData')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Project_ID', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('Start_year', models.IntegerField(default=2022)),
                ('Interactions_count', models.IntegerField(default=0)),
                ('Interaction_1', models.CharField(blank=True, max_length=120, null=True)),
                ('Interaction_2', models.CharField(blank=True, max_length=120, null=True)),
                ('Interaction_3', models.CharField(blank=True, max_length=120, null=True)),
                ('Crop', models.CharField(choices=[('Select', 'select'), ('NA', 'Not Available'), ('Corn', 'Corn'), ('Cotton', 'Cotton'), ('Rice', 'Rice'), ('Fescue', 'Fescue')], default='NA', max_length=50)),
                ('No_of_Year', models.IntegerField(default=1)),
                ('Role', models.CharField(choices=[('Select', 'select'), ('Researcher', 'Researcher'), ('Manager', 'Manager'), ('Administrator', 'Administrator')], default='Researcher', max_length=100)),
                ('Funding_Source', models.CharField(default='Unknown', max_length=100)),
                ('MetaData', models.TextField(default='No metadata available')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('Experiment_ID', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='Experiment_ID')),
                ('Year', models.CharField(max_length=120, verbose_name='Year')),
                ('Interaction_1_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Interaction_1_count')),
                ('Interaction_1_count_1', models.CharField(default='NA', max_length=120, verbose_name='Interaction_1_count_1')),
                ('Interaction_1_count_2', models.CharField(default='NA', max_length=120, verbose_name='Interaction_1_count_2')),
                ('Interaction_1_count_3', models.CharField(default='NA', max_length=120, verbose_name='Interaction_1_count_3')),
                ('Interaction_1_count_4', models.CharField(default='NA', max_length=120, verbose_name='Interaction_1_count_4')),
                ('Interaction_1_count_5', models.CharField(default='NA', max_length=120, verbose_name='Interaction_1_count_5')),
                ('Interaction_2_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Interaction_2_count')),
                ('Interaction_2_count_1', models.CharField(default='NA', max_length=120, verbose_name='Interaction_2_count_1')),
                ('Interaction_2_count_2', models.CharField(default='NA', max_length=120, verbose_name='Interaction_2_count_2')),
                ('Interaction_2_count_3', models.CharField(default='NA', max_length=120, verbose_name='Interaction_2_count_3')),
                ('Interaction_2_count_4', models.CharField(default='NA', max_length=120, verbose_name='Interaction_2_count_4')),
                ('Interaction_2_count_5', models.CharField(default='NA', max_length=120, verbose_name='Interaction_2_count_5')),
                ('Interaction_3_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Interaction_3_count')),
                ('Interaction_3_count_1', models.CharField(default='NA', max_length=120, verbose_name='Interaction_3_count_1')),
                ('Interaction_3_count_2', models.CharField(default='NA', max_length=120, verbose_name='Interaction_3_count_2')),
                ('Interaction_3_count_3', models.CharField(default='NA', max_length=120, verbose_name='Interaction_3_count_3')),
                ('Interaction_3_count_4', models.CharField(default='NA', max_length=120, verbose_name='Interaction_3_count_4')),
                ('Interaction_3_count_5', models.CharField(default='NA', max_length=120, verbose_name='Interaction_3_count_5')),
                ('MetaData', models.TextField(max_length=120, verbose_name='MetaData')),
                ('Location_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='N_trail_dashboard.location')),
                ('Project_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='N_trail_dashboard.project')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('Treatment_ID', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='Treatment_ID')),
                ('Interaction_1_Value', models.CharField(max_length=120, verbose_name='Interaction_1_Value')),
                ('Interaction_2_Value', models.CharField(max_length=120, verbose_name='Interaction_2_Value')),
                ('Interaction_3_Value', models.CharField(max_length=120, verbose_name='Interaction_3_Value')),
                ('No_of_Replication', models.CharField(max_length=120, verbose_name='No_of_Replication')),
                ('MetaData', models.TextField(max_length=120, verbose_name='MetaData')),
                ('Experiment_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='N_trail_dashboard.experiment')),
            ],
        ),
    ]
