# Generated by Django 5.0.6 on 2024-06-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('N_trail_dashboard', '0004_remove_experiment_interaction_1_count_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Role',
        ),
        migrations.AddField(
            model_name='project',
            name='Project_Editors',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
