# Generated by Django 5.0.6 on 2024-06-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('N_trail_dashboard', '0006_project_view_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Crop',
            field=models.CharField(choices=[('', 'select'), ('NA', 'Not Available'), ('Corn', 'Corn'), ('Cotton', 'Cotton'), ('Rice', 'Rice'), ('Fescue', 'Fescue')], default='NA', max_length=50),
        ),
    ]
