# Generated by Django 5.0.6 on 2024-06-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('N_trail_dashboard', '0012_alter_project_view_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='No_of_Year',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Start_year',
        ),
        migrations.AlterField(
            model_name='project',
            name='View_Type',
            field=models.CharField(choices=[('', 'select'), ('public', 'Public'), ('protected', 'Protected')], default='private', max_length=10),
        ),
    ]
