# Generated by Django 5.0.6 on 2024-06-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('N_trail_dashboard', '0013_remove_project_no_of_year_remove_project_start_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='Units',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Units'),
        ),
        migrations.AddField(
            model_name='plot',
            name='Yield',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
